### ISSUE TITLE
Form page is broken on demo site

### ISSUE THREAD

**Issue by andyError** [grommet/grommet-theme-designer#7] opened 2020-06-10 14:53 UTC
If you visit https://theme-designer.grommet.io/Form the you just get a blank white screen with bugs in the console. Tested in Chrome and FF on Mac.

**Comment by ericsoderberghp** [comment] 2020-10-06 15:51
I am unable to reproduce this issue. Perhaps it was fixed in a subsequent change. Please re-open this issue if you are still encountering it.

**Closed as completed by ericsoderberghp** 2020-10-06 15:51 UTC
